name: Build driver solution
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug]
        platform: [x64]
    runs-on: windows-2022
    env:
      Solution_Path: MoonMon.sln
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Enable Node 16
        run: |
          echo "ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION=true" >> $GITHUB_ENV

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Build solution
        run: |
          msbuild ${{ env.Solution_Path }} /property:Configuration=${{ env.Configuration }} /property:Platform=${{ env.Platform }} 

        env:
          Configuration: ${{ matrix.configuration }}
          Platform: ${{ matrix.platform }}

      - name: Build result
        run: |
          cd ${{ matrix.platform }}/${{ matrix.configuration }}
          dir

